# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooktaskorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='waitertaskorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='waitertaskorder',
            name='task',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='orders',
        ),
        migrations.AddField(
            model_name='waiterorder',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cook.WaiterTask'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CookTaskOrder',
        ),
        migrations.DeleteModel(
            name='WaiterTaskOrder',
        ),
    ]
