# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_remove_waiterorder_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('0', 'started'), ('1', 'ready'), ('2', 'done')], default='0', max_length=1)),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='waiterorder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.WaiterOrderDetails'),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='state',
            field=models.CharField(choices=[('0', 'started'), ('1', 'done')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='waiterorderdetails',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.WaiterTask'),
        ),
    ]
