# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_auto_20181130_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='dishtranslation',
            name='name',
            field=models.CharField(default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(default='...', max_length=50),
        ),
    ]
