# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.CharField(choices=[('0', 'active'), ('1', 'notactive')], default='0', max_length=1),
        ),
    ]
