# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0011_notification_active'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='name',
        ),
    ]
