# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0017_auto_20190113_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dishproduct',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
