# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0018_auto_20190115_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(default='...', max_length=300, null=True),
        ),
    ]
