# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0007_auto_20180213_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooktask',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cooktask',
            name='state',
            field=models.CharField(choices=[('0', 'started'), ('1', 'ready'), ('2', 'done')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='cooktask',
            name='comment',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
