# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0010_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DishPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishprice',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cook.RestaurantDetails'),
        ),
    ]
