# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0011_auto_20181107_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantDetails',
            new_name='RestaurantDetail',
        ),
        migrations.AddField(
            model_name='dish',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=4),
            preserve_default=False,
        ),
    ]
