# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0012_auto_20181107_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
