# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0020_auto_20181108_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishorder',
            name='dish',
        ),
        migrations.AddField(
            model_name='cooktask',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook', to='cook.Employee'),
        ),
        migrations.AddField(
            model_name='cooktask',
            name='count',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='cook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cook.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='count',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cook.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='price_default',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='prices',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.RemoveField(
            model_name='cooktask',
            name='products',
        ),
        migrations.AddField(
            model_name='cooktask',
            name='products',
            field=models.ManyToManyField(to='cook.Product'),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='dishes',
            field=models.ManyToManyField(to='cook.Dish'),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter', to='cook.Employee'),
        ),
        migrations.DeleteModel(
            name='DishOrder',
        ),
    ]
