# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 17:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0022_auto_20181114_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookTaskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WaiterTaskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='orders',
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waiterorder',
            name='level',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='levels',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_category_name', message='Category name must be Alphanumeric', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='cookorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cook.Product'),
        ),
        migrations.AlterField(
            model_name='cooktask',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='orders', through='cook.CookTaskOrder', to='cook.CookOrder'),
        ),
        migrations.AddField(
            model_name='waitertaskorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterOrder'),
        ),
        migrations.AddField(
            model_name='waitertaskorder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterTask'),
        ),
        migrations.AddField(
            model_name='cooktaskorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.CookOrder'),
        ),
        migrations.AddField(
            model_name='cooktaskorder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.CookTask'),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='waiterorders',
            field=models.ManyToManyField(related_name='orders', through='cook.WaiterTaskOrder', to='cook.WaiterOrder'),
        ),
    ]
