# Generated by Django 2.0.1 on 2018-01-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CookTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(default=' ', max_length=300)),
                ('priority', models.CharField(choices=[('0', 'normal'), ('1', 'important'), ('2', 'for yesterday')], default='0', max_length=1)),
                ('comment', models.CharField(default=' ', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('av', models.CharField(choices=[('0', 'available'), ('1', 'not available')], max_length=1)),
                ('products', models.CharField(default=' ', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('0', 'waiter'), ('1', 'cook'), ('2', 'provaider')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('av', models.CharField(choices=[('0', 'small'), ('1', 'medium'), ('2', 'large')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WaiterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter', models.CharField(max_length=50)),
                ('table', models.IntegerField()),
                ('state', models.CharField(choices=[('0', 'started'), ('1', 'ready'), ('2', 'done')], default='0', max_length=1)),
                ('comment', models.CharField(default=' ', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(to='cook.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='cooktask',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Employee'),
        ),
    ]
