# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitertask',
            name='istakeaway',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
