# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_auto_20190121_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitertask',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='cook.Employee'),
        ),
    ]
