# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_waitertask_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='supply',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='suply',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], default='0', max_length=1),
        ),
    ]
