# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20180114_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='products',
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(to='cook.Product'),
        ),
    ]
