# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 22:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20181126_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DishTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=50, unique=True)),
                ('description', models.CharField(default='...', max_length=300)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_category_name', message='Category name must be Alphanumeric', regex='^[a-zA-Z]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=50, unique=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Product')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='ab',
            field=models.CharField(default='zł', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishtranslation',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Language'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Language'),
        ),
    ]
