# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20190122_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooktask',
            name='reservation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='reservation',
            field=models.DateTimeField(null=True),
        ),
    ]
