# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20180114_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitertask',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Employee'),
        ),
    ]
