# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_auto_20181129_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ab',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(default='...', max_length=300),
        ),
    ]
