# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_auto_20180127_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
