# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0007_auto_20181130_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='default_lang',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='cook.Language'),
            preserve_default=False,
        ),
    ]
