# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0008_auto_20180219_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish')),
            ],
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='dishes',
            field=models.ManyToManyField(to='cook.DishOrder'),
        ),
    ]
