# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0009_auto_20180302_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('0', 'offline'), ('1', 'notactive'), ('2', 'active')], default='0', max_length=1),
        ),
    ]
