# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 18:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cook', '0009_auto_20180302_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DishPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'offline'), ('1', 'notactive'), ('2', 'active')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaiterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_default', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='WaiterTaskOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='dishorder',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cooktask',
            name='products',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='dishes',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='kg', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_category_name', message='Category name must be Alphanumeric', regex='^[a-zA-Z]*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooktask',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook', to='cook.Employee'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.CharField(choices=[('0', 'active'), ('1', 'notactive')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('0', 'offline'), ('1', 'notactive'), ('2', 'active')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='cook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cook.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='levels',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='price_default',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cooktask',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter', to='cook.Employee'),
        ),
        migrations.DeleteModel(
            name='DishOrder',
        ),
        migrations.AddField(
            model_name='waitertaskorder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterTask'),
        ),
        migrations.AddField(
            model_name='waiterorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Employee'),
        ),
        migrations.AddField(
            model_name='dishprice',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish'),
        ),
        migrations.AddField(
            model_name='cookorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cook.Product'),
        ),
        migrations.AddField(
            model_name='cooktask',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='orders', to='cook.CookOrder'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cook.RestaurantDetail'),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cook.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='orders',
            field=models.ManyToManyField(related_name='orders', through='cook.WaiterTaskOrder', to='cook.WaiterOrder'),
        ),
    ]
