# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0014_auto_20190102_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=50)),
                ('count', models.DecimalField(decimal_places=0, max_digits=2)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Product')),
            ],
        ),
    ]
