# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0014_restaurantdetail_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetail',
            name='default_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency'),
        ),
    ]
