# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0016_auto_20181107_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
