# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0019_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.CharField(choices=[('0', 'active'), ('1', 'notactive')], default='0', max_length=1),
        ),
    ]
