# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0021_auto_20181114_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Product')),
            ],
        ),
        migrations.CreateModel(
            name='WaiterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_default', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Currency')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Dish')),
            ],
        ),
        migrations.RemoveField(
            model_name='cooktask',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cooktask',
            name='products',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='count',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='prices',
        ),
        migrations.AlterField(
            model_name='cooktask',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='waitertask',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cooktask',
            name='orders',
            field=models.ManyToManyField(to='cook.CookOrder'),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='orders',
            field=models.ManyToManyField(to='cook.WaiterOrder'),
        ),
    ]
