# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0022_auto_20181114_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterorder',
            name='level',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitertask',
            name='levels',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
