# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0023_auto_20181115_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
