# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0024_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_category_name', message='Category name must be Alphanumeric', regex='^[a-zA-Z]*$')]),
        ),
    ]
