# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0025_auto_20181116_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=8),
            preserve_default=False,
        ),
    ]
