# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0027_auto_20181120_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterOrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='waitertask',
            name='orders',
        ),
        migrations.AddField(
            model_name='waiterordertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cook.WaiterTask'),
        ),
        migrations.AddField(
            model_name='waitertask',
            name='waiterorders',
            field=models.ManyToManyField(related_name='orders', through='cook.WaiterOrderTask', to='cook.WaiterOrder'),
        ),
    ]
