# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0028_auto_20181120_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooktask',
            name='cookorders',
            field=models.ManyToManyField(null=True, related_name='orders', through='cook.CookOrderTask', to='cook.CookOrder'),
        ),
    ]
